/* Generated By:JavaCC: Do not edit this line. ExparserImplConstants.java */
package com.yunpayroll.exparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExparserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int ABS = 2;
  /** RegularExpression Id. */
  int ABSENT = 3;
  /** RegularExpression Id. */
  int ABSOLUTE = 4;
  /** RegularExpression Id. */
  int ACTION = 5;
  /** RegularExpression Id. */
  int ADA = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int ADMIN = 8;
  /** RegularExpression Id. */
  int AFTER = 9;
  /** RegularExpression Id. */
  int ALL = 10;
  /** RegularExpression Id. */
  int ALLOCATE = 11;
  /** RegularExpression Id. */
  int ALLOW = 12;
  /** RegularExpression Id. */
  int ALTER = 13;
  /** RegularExpression Id. */
  int ALWAYS = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int ANY = 16;
  /** RegularExpression Id. */
  int APPLY = 17;
  /** RegularExpression Id. */
  int ARE = 18;
  /** RegularExpression Id. */
  int ARRAY = 19;
  /** RegularExpression Id. */
  int ARRAY_MAX_CARDINALITY = 20;
  /** RegularExpression Id. */
  int AS = 21;
  /** RegularExpression Id. */
  int ASC = 22;
  /** RegularExpression Id. */
  int ASENSITIVE = 23;
  /** RegularExpression Id. */
  int ASSERTION = 24;
  /** RegularExpression Id. */
  int ASSIGNMENT = 25;
  /** RegularExpression Id. */
  int ASYMMETRIC = 26;
  /** RegularExpression Id. */
  int AT = 27;
  /** RegularExpression Id. */
  int ATOMIC = 28;
  /** RegularExpression Id. */
  int ATTRIBUTE = 29;
  /** RegularExpression Id. */
  int ATTRIBUTES = 30;
  /** RegularExpression Id. */
  int AUTHORIZATION = 31;
  /** RegularExpression Id. */
  int AVG = 32;
  /** RegularExpression Id. */
  int BEFORE = 33;
  /** RegularExpression Id. */
  int BEGIN = 34;
  /** RegularExpression Id. */
  int BEGIN_FRAME = 35;
  /** RegularExpression Id. */
  int BEGIN_PARTITION = 36;
  /** RegularExpression Id. */
  int BERNOULLI = 37;
  /** RegularExpression Id. */
  int BETWEEN = 38;
  /** RegularExpression Id. */
  int BIGINT = 39;
  /** RegularExpression Id. */
  int BINARY = 40;
  /** RegularExpression Id. */
  int BIT = 41;
  /** RegularExpression Id. */
  int BLOB = 42;
  /** RegularExpression Id. */
  int BOOLEAN = 43;
  /** RegularExpression Id. */
  int BOTH = 44;
  /** RegularExpression Id. */
  int BREADTH = 45;
  /** RegularExpression Id. */
  int BY = 46;
  /** RegularExpression Id. */
  int C = 47;
  /** RegularExpression Id. */
  int CALL = 48;
  /** RegularExpression Id. */
  int CALLED = 49;
  /** RegularExpression Id. */
  int CARDINALITY = 50;
  /** RegularExpression Id. */
  int CASCADE = 51;
  /** RegularExpression Id. */
  int CASCADED = 52;
  /** RegularExpression Id. */
  int CASE = 53;
  /** RegularExpression Id. */
  int CAST = 54;
  /** RegularExpression Id. */
  int CATALOG = 55;
  /** RegularExpression Id. */
  int CATALOG_NAME = 56;
  /** RegularExpression Id. */
  int CEIL = 57;
  /** RegularExpression Id. */
  int CEILING = 58;
  /** RegularExpression Id. */
  int CENTURY = 59;
  /** RegularExpression Id. */
  int CHAIN = 60;
  /** RegularExpression Id. */
  int CHAR = 61;
  /** RegularExpression Id. */
  int CHAR_LENGTH = 62;
  /** RegularExpression Id. */
  int CHARACTER = 63;
  /** RegularExpression Id. */
  int CHARACTER_LENGTH = 64;
  /** RegularExpression Id. */
  int CHARACTER_SET_CATALOG = 65;
  /** RegularExpression Id. */
  int CHARACTER_SET_NAME = 66;
  /** RegularExpression Id. */
  int CHARACTER_SET_SCHEMA = 67;
  /** RegularExpression Id. */
  int CHARACTERISTICS = 68;
  /** RegularExpression Id. */
  int CHARACTERS = 69;
  /** RegularExpression Id. */
  int CHECK = 70;
  /** RegularExpression Id. */
  int CLASSIFIER = 71;
  /** RegularExpression Id. */
  int CLASS_ORIGIN = 72;
  /** RegularExpression Id. */
  int CLOB = 73;
  /** RegularExpression Id. */
  int CLOSE = 74;
  /** RegularExpression Id. */
  int COALESCE = 75;
  /** RegularExpression Id. */
  int COBOL = 76;
  /** RegularExpression Id. */
  int COLLATE = 77;
  /** RegularExpression Id. */
  int COLLATION = 78;
  /** RegularExpression Id. */
  int COLLATION_CATALOG = 79;
  /** RegularExpression Id. */
  int COLLATION_NAME = 80;
  /** RegularExpression Id. */
  int COLLATION_SCHEMA = 81;
  /** RegularExpression Id. */
  int COLLECT = 82;
  /** RegularExpression Id. */
  int COLUMN = 83;
  /** RegularExpression Id. */
  int COLUMN_NAME = 84;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION = 85;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION_CODE = 86;
  /** RegularExpression Id. */
  int COMMIT = 87;
  /** RegularExpression Id. */
  int COMMITTED = 88;
  /** RegularExpression Id. */
  int CONDITION = 89;
  /** RegularExpression Id. */
  int CONDITIONAL = 90;
  /** RegularExpression Id. */
  int CONDITION_NUMBER = 91;
  /** RegularExpression Id. */
  int CONNECT = 92;
  /** RegularExpression Id. */
  int CONNECTION = 93;
  /** RegularExpression Id. */
  int CONNECTION_NAME = 94;
  /** RegularExpression Id. */
  int CONSTRAINT = 95;
  /** RegularExpression Id. */
  int CONSTRAINT_CATALOG = 96;
  /** RegularExpression Id. */
  int CONSTRAINT_NAME = 97;
  /** RegularExpression Id. */
  int CONSTRAINT_SCHEMA = 98;
  /** RegularExpression Id. */
  int CONSTRAINTS = 99;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 100;
  /** RegularExpression Id. */
  int CONTAINS = 101;
  /** RegularExpression Id. */
  int CONTINUE = 102;
  /** RegularExpression Id. */
  int CONVERT = 103;
  /** RegularExpression Id. */
  int CORR = 104;
  /** RegularExpression Id. */
  int CORRESPONDING = 105;
  /** RegularExpression Id. */
  int COUNT = 106;
  /** RegularExpression Id. */
  int COVAR_POP = 107;
  /** RegularExpression Id. */
  int COVAR_SAMP = 108;
  /** RegularExpression Id. */
  int CREATE = 109;
  /** RegularExpression Id. */
  int CROSS = 110;
  /** RegularExpression Id. */
  int CUBE = 111;
  /** RegularExpression Id. */
  int CUME_DIST = 112;
  /** RegularExpression Id. */
  int CURRENT = 113;
  /** RegularExpression Id. */
  int CURRENT_CATALOG = 114;
  /** RegularExpression Id. */
  int CURRENT_DATE = 115;
  /** RegularExpression Id. */
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 116;
  /** RegularExpression Id. */
  int CURRENT_PATH = 117;
  /** RegularExpression Id. */
  int CURRENT_ROLE = 118;
  /** RegularExpression Id. */
  int CURRENT_ROW = 119;
  /** RegularExpression Id. */
  int CURRENT_SCHEMA = 120;
  /** RegularExpression Id. */
  int CURRENT_TIME = 121;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 122;
  /** RegularExpression Id. */
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 123;
  /** RegularExpression Id. */
  int CURRENT_USER = 124;
  /** RegularExpression Id. */
  int CURSOR = 125;
  /** RegularExpression Id. */
  int CURSOR_NAME = 126;
  /** RegularExpression Id. */
  int CYCLE = 127;
  /** RegularExpression Id. */
  int DATA = 128;
  /** RegularExpression Id. */
  int DATABASE = 129;
  /** RegularExpression Id. */
  int DATE = 130;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_CODE = 131;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_PRECISION = 132;
  /** RegularExpression Id. */
  int DAY = 133;
  /** RegularExpression Id. */
  int DEALLOCATE = 134;
  /** RegularExpression Id. */
  int DEC = 135;
  /** RegularExpression Id. */
  int DECADE = 136;
  /** RegularExpression Id. */
  int DECIMAL = 137;
  /** RegularExpression Id. */
  int DECLARE = 138;
  /** RegularExpression Id. */
  int DEFAULT_ = 139;
  /** RegularExpression Id. */
  int DEFAULTS = 140;
  /** RegularExpression Id. */
  int DEFERRABLE = 141;
  /** RegularExpression Id. */
  int DEFERRED = 142;
  /** RegularExpression Id. */
  int DEFINE = 143;
  /** RegularExpression Id. */
  int DEFINED = 144;
  /** RegularExpression Id. */
  int DEFINER = 145;
  /** RegularExpression Id. */
  int DEGREE = 146;
  /** RegularExpression Id. */
  int DELETE = 147;
  /** RegularExpression Id. */
  int DENSE_RANK = 148;
  /** RegularExpression Id. */
  int DEPTH = 149;
  /** RegularExpression Id. */
  int DEREF = 150;
  /** RegularExpression Id. */
  int DERIVED = 151;
  /** RegularExpression Id. */
  int DESC = 152;
  /** RegularExpression Id. */
  int DESCRIBE = 153;
  /** RegularExpression Id. */
  int DESCRIPTION = 154;
  /** RegularExpression Id. */
  int DESCRIPTOR = 155;
  /** RegularExpression Id. */
  int DETERMINISTIC = 156;
  /** RegularExpression Id. */
  int DIAGNOSTICS = 157;
  /** RegularExpression Id. */
  int DISALLOW = 158;
  /** RegularExpression Id. */
  int DISCONNECT = 159;
  /** RegularExpression Id. */
  int DISPATCH = 160;
  /** RegularExpression Id. */
  int DISTINCT = 161;
  /** RegularExpression Id. */
  int DOMAIN = 162;
  /** RegularExpression Id. */
  int DOUBLE = 163;
  /** RegularExpression Id. */
  int DOW = 164;
  /** RegularExpression Id. */
  int DOY = 165;
  /** RegularExpression Id. */
  int DROP = 166;
  /** RegularExpression Id. */
  int DYNAMIC = 167;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION = 168;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION_CODE = 169;
  /** RegularExpression Id. */
  int EACH = 170;
  /** RegularExpression Id. */
  int ELEMENT = 171;
  /** RegularExpression Id. */
  int ELSE = 172;
  /** RegularExpression Id. */
  int EMPTY = 173;
  /** RegularExpression Id. */
  int ENCODING = 174;
  /** RegularExpression Id. */
  int END = 175;
  /** RegularExpression Id. */
  int END_EXEC = 176;
  /** RegularExpression Id. */
  int END_FRAME = 177;
  /** RegularExpression Id. */
  int END_PARTITION = 178;
  /** RegularExpression Id. */
  int EPOCH = 179;
  /** RegularExpression Id. */
  int EQUALS = 180;
  /** RegularExpression Id. */
  int ERROR = 181;
  /** RegularExpression Id. */
  int ESCAPE = 182;
  /** RegularExpression Id. */
  int EVERY = 183;
  /** RegularExpression Id. */
  int EXCEPT = 184;
  /** RegularExpression Id. */
  int EXCEPTION = 185;
  /** RegularExpression Id. */
  int EXCLUDE = 186;
  /** RegularExpression Id. */
  int EXCLUDING = 187;
  /** RegularExpression Id. */
  int EXEC = 188;
  /** RegularExpression Id. */
  int EXECUTE = 189;
  /** RegularExpression Id. */
  int EXISTS = 190;
  /** RegularExpression Id. */
  int EXP = 191;
  /** RegularExpression Id. */
  int EXPLAIN = 192;
  /** RegularExpression Id. */
  int EXTEND = 193;
  /** RegularExpression Id. */
  int EXTERNAL = 194;
  /** RegularExpression Id. */
  int EXTRACT = 195;
  /** RegularExpression Id. */
  int FALSE = 196;
  /** RegularExpression Id. */
  int FETCH = 197;
  /** RegularExpression Id. */
  int FILTER = 198;
  /** RegularExpression Id. */
  int FINAL = 199;
  /** RegularExpression Id. */
  int FIRST = 200;
  /** RegularExpression Id. */
  int FIRST_VALUE = 201;
  /** RegularExpression Id. */
  int FLOAT = 202;
  /** RegularExpression Id. */
  int FLOOR = 203;
  /** RegularExpression Id. */
  int FOLLOWING = 204;
  /** RegularExpression Id. */
  int FOR = 205;
  /** RegularExpression Id. */
  int FORMAT = 206;
  /** RegularExpression Id. */
  int FOREIGN = 207;
  /** RegularExpression Id. */
  int FORTRAN = 208;
  /** RegularExpression Id. */
  int FOUND = 209;
  /** RegularExpression Id. */
  int FRAC_SECOND = 210;
  /** RegularExpression Id. */
  int FRAME_ROW = 211;
  /** RegularExpression Id. */
  int FREE = 212;
  /** RegularExpression Id. */
  int FROM = 213;
  /** RegularExpression Id. */
  int FULL = 214;
  /** RegularExpression Id. */
  int FUNCTION = 215;
  /** RegularExpression Id. */
  int FUSION = 216;
  /** RegularExpression Id. */
  int G = 217;
  /** RegularExpression Id. */
  int GENERAL = 218;
  /** RegularExpression Id. */
  int GENERATED = 219;
  /** RegularExpression Id. */
  int GEOMETRY = 220;
  /** RegularExpression Id. */
  int GET = 221;
  /** RegularExpression Id. */
  int GLOBAL = 222;
  /** RegularExpression Id. */
  int GO = 223;
  /** RegularExpression Id. */
  int GOTO = 224;
  /** RegularExpression Id. */
  int GRANT = 225;
  /** RegularExpression Id. */
  int GRANTED = 226;
  /** RegularExpression Id. */
  int GROUP = 227;
  /** RegularExpression Id. */
  int GROUPING = 228;
  /** RegularExpression Id. */
  int GROUPS = 229;
  /** RegularExpression Id. */
  int HAVING = 230;
  /** RegularExpression Id. */
  int HIERARCHY = 231;
  /** RegularExpression Id. */
  int HOLD = 232;
  /** RegularExpression Id. */
  int HOUR = 233;
  /** RegularExpression Id. */
  int IDENTITY = 234;
  /** RegularExpression Id. */
  int IGNORE = 235;
  /** RegularExpression Id. */
  int IMMEDIATE = 236;
  /** RegularExpression Id. */
  int IMMEDIATELY = 237;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 238;
  /** RegularExpression Id. */
  int IMPORT = 239;
  /** RegularExpression Id. */
  int IN = 240;
  /** RegularExpression Id. */
  int INCLUDING = 241;
  /** RegularExpression Id. */
  int INCREMENT = 242;
  /** RegularExpression Id. */
  int INDICATOR = 243;
  /** RegularExpression Id. */
  int INITIAL = 244;
  /** RegularExpression Id. */
  int INITIALLY = 245;
  /** RegularExpression Id. */
  int INNER = 246;
  /** RegularExpression Id. */
  int INOUT = 247;
  /** RegularExpression Id. */
  int INPUT = 248;
  /** RegularExpression Id. */
  int INSENSITIVE = 249;
  /** RegularExpression Id. */
  int INSERT = 250;
  /** RegularExpression Id. */
  int INSTANCE = 251;
  /** RegularExpression Id. */
  int INSTANTIABLE = 252;
  /** RegularExpression Id. */
  int INT = 253;
  /** RegularExpression Id. */
  int INTEGER = 254;
  /** RegularExpression Id. */
  int INTERSECT = 255;
  /** RegularExpression Id. */
  int INTERSECTION = 256;
  /** RegularExpression Id. */
  int INTERVAL = 257;
  /** RegularExpression Id. */
  int INTO = 258;
  /** RegularExpression Id. */
  int INVOKER = 259;
  /** RegularExpression Id. */
  int IS = 260;
  /** RegularExpression Id. */
  int ISODOW = 261;
  /** RegularExpression Id. */
  int ISOYEAR = 262;
  /** RegularExpression Id. */
  int ISOLATION = 263;
  /** RegularExpression Id. */
  int JAVA = 264;
  /** RegularExpression Id. */
  int JOIN = 265;
  /** RegularExpression Id. */
  int JSON = 266;
  /** RegularExpression Id. */
  int JSON_ARRAY = 267;
  /** RegularExpression Id. */
  int JSON_ARRAYAGG = 268;
  /** RegularExpression Id. */
  int JSON_EXISTS = 269;
  /** RegularExpression Id. */
  int JSON_OBJECT = 270;
  /** RegularExpression Id. */
  int JSON_OBJECTAGG = 271;
  /** RegularExpression Id. */
  int JSON_QUERY = 272;
  /** RegularExpression Id. */
  int JSON_VALUE = 273;
  /** RegularExpression Id. */
  int K = 274;
  /** RegularExpression Id. */
  int KEY = 275;
  /** RegularExpression Id. */
  int KEY_MEMBER = 276;
  /** RegularExpression Id. */
  int KEY_TYPE = 277;
  /** RegularExpression Id. */
  int LABEL = 278;
  /** RegularExpression Id. */
  int LAG = 279;
  /** RegularExpression Id. */
  int LANGUAGE = 280;
  /** RegularExpression Id. */
  int LARGE = 281;
  /** RegularExpression Id. */
  int LAST = 282;
  /** RegularExpression Id. */
  int LAST_VALUE = 283;
  /** RegularExpression Id. */
  int LATERAL = 284;
  /** RegularExpression Id. */
  int LEAD = 285;
  /** RegularExpression Id. */
  int LEADING = 286;
  /** RegularExpression Id. */
  int LEFT = 287;
  /** RegularExpression Id. */
  int LENGTH = 288;
  /** RegularExpression Id. */
  int LEVEL = 289;
  /** RegularExpression Id. */
  int LIBRARY = 290;
  /** RegularExpression Id. */
  int LIKE = 291;
  /** RegularExpression Id. */
  int LIKE_REGEX = 292;
  /** RegularExpression Id. */
  int LIMIT = 293;
  /** RegularExpression Id. */
  int LN = 294;
  /** RegularExpression Id. */
  int LOCAL = 295;
  /** RegularExpression Id. */
  int LOCALTIME = 296;
  /** RegularExpression Id. */
  int LOCALTIMESTAMP = 297;
  /** RegularExpression Id. */
  int LOCATOR = 298;
  /** RegularExpression Id. */
  int LOWER = 299;
  /** RegularExpression Id. */
  int M = 300;
  /** RegularExpression Id. */
  int MAP = 301;
  /** RegularExpression Id. */
  int MATCH = 302;
  /** RegularExpression Id. */
  int MATCHED = 303;
  /** RegularExpression Id. */
  int MATCHES = 304;
  /** RegularExpression Id. */
  int MATCH_NUMBER = 305;
  /** RegularExpression Id. */
  int MATCH_RECOGNIZE = 306;
  /** RegularExpression Id. */
  int MAX = 307;
  /** RegularExpression Id. */
  int MAXVALUE = 308;
  /** RegularExpression Id. */
  int MEASURES = 309;
  /** RegularExpression Id. */
  int MEMBER = 310;
  /** RegularExpression Id. */
  int MERGE = 311;
  /** RegularExpression Id. */
  int MESSAGE_LENGTH = 312;
  /** RegularExpression Id. */
  int MESSAGE_OCTET_LENGTH = 313;
  /** RegularExpression Id. */
  int MESSAGE_TEXT = 314;
  /** RegularExpression Id. */
  int METHOD = 315;
  /** RegularExpression Id. */
  int MICROSECOND = 316;
  /** RegularExpression Id. */
  int MILLISECOND = 317;
  /** RegularExpression Id. */
  int MILLENNIUM = 318;
  /** RegularExpression Id. */
  int MIN = 319;
  /** RegularExpression Id. */
  int MINUTE = 320;
  /** RegularExpression Id. */
  int MINVALUE = 321;
  /** RegularExpression Id. */
  int MOD = 322;
  /** RegularExpression Id. */
  int MODIFIES = 323;
  /** RegularExpression Id. */
  int MODULE = 324;
  /** RegularExpression Id. */
  int MONTH = 325;
  /** RegularExpression Id. */
  int MORE_ = 326;
  /** RegularExpression Id. */
  int MULTISET = 327;
  /** RegularExpression Id. */
  int MUMPS = 328;
  /** RegularExpression Id. */
  int NAME = 329;
  /** RegularExpression Id. */
  int NAMES = 330;
  /** RegularExpression Id. */
  int NANOSECOND = 331;
  /** RegularExpression Id. */
  int NATIONAL = 332;
  /** RegularExpression Id. */
  int NATURAL = 333;
  /** RegularExpression Id. */
  int NCHAR = 334;
  /** RegularExpression Id. */
  int NCLOB = 335;
  /** RegularExpression Id. */
  int NESTING = 336;
  /** RegularExpression Id. */
  int NEW = 337;
  /** RegularExpression Id. */
  int NEXT = 338;
  /** RegularExpression Id. */
  int NO = 339;
  /** RegularExpression Id. */
  int NONE = 340;
  /** RegularExpression Id. */
  int NORMALIZE = 341;
  /** RegularExpression Id. */
  int NORMALIZED = 342;
  /** RegularExpression Id. */
  int NOT = 343;
  /** RegularExpression Id. */
  int NTH_VALUE = 344;
  /** RegularExpression Id. */
  int NTILE = 345;
  /** RegularExpression Id. */
  int NULL = 346;
  /** RegularExpression Id. */
  int NULLABLE = 347;
  /** RegularExpression Id. */
  int NULLIF = 348;
  /** RegularExpression Id. */
  int NULLS = 349;
  /** RegularExpression Id. */
  int NUMBER = 350;
  /** RegularExpression Id. */
  int NUMERIC = 351;
  /** RegularExpression Id. */
  int OBJECT = 352;
  /** RegularExpression Id. */
  int OCCURRENCES_REGEX = 353;
  /** RegularExpression Id. */
  int OCTET_LENGTH = 354;
  /** RegularExpression Id. */
  int OCTETS = 355;
  /** RegularExpression Id. */
  int OF = 356;
  /** RegularExpression Id. */
  int OFFSET = 357;
  /** RegularExpression Id. */
  int OLD = 358;
  /** RegularExpression Id. */
  int OMIT = 359;
  /** RegularExpression Id. */
  int ON = 360;
  /** RegularExpression Id. */
  int ONE = 361;
  /** RegularExpression Id. */
  int ONLY = 362;
  /** RegularExpression Id. */
  int OPEN = 363;
  /** RegularExpression Id. */
  int OPTION = 364;
  /** RegularExpression Id. */
  int OPTIONS = 365;
  /** RegularExpression Id. */
  int OR = 366;
  /** RegularExpression Id. */
  int ORDER = 367;
  /** RegularExpression Id. */
  int ORDERING = 368;
  /** RegularExpression Id. */
  int ORDINALITY = 369;
  /** RegularExpression Id. */
  int OTHERS = 370;
  /** RegularExpression Id. */
  int OUT = 371;
  /** RegularExpression Id. */
  int OUTER = 372;
  /** RegularExpression Id. */
  int OUTPUT = 373;
  /** RegularExpression Id. */
  int OVER = 374;
  /** RegularExpression Id. */
  int OVERLAPS = 375;
  /** RegularExpression Id. */
  int OVERLAY = 376;
  /** RegularExpression Id. */
  int OVERRIDING = 377;
  /** RegularExpression Id. */
  int PAD = 378;
  /** RegularExpression Id. */
  int PARAMETER = 379;
  /** RegularExpression Id. */
  int PARAMETER_MODE = 380;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 381;
  /** RegularExpression Id. */
  int PARAMETER_ORDINAL_POSITION = 382;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_CATALOG = 383;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_NAME = 384;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_SCHEMA = 385;
  /** RegularExpression Id. */
  int PARTIAL = 386;
  /** RegularExpression Id. */
  int PARTITION = 387;
  /** RegularExpression Id. */
  int PASCAL = 388;
  /** RegularExpression Id. */
  int PASSING = 389;
  /** RegularExpression Id. */
  int PASSTHROUGH = 390;
  /** RegularExpression Id. */
  int PAST = 391;
  /** RegularExpression Id. */
  int PATH = 392;
  /** RegularExpression Id. */
  int PATTERN = 393;
  /** RegularExpression Id. */
  int PER = 394;
  /** RegularExpression Id. */
  int PERCENT = 395;
  /** RegularExpression Id. */
  int PERCENTILE_CONT = 396;
  /** RegularExpression Id. */
  int PERCENTILE_DISC = 397;
  /** RegularExpression Id. */
  int PERCENT_RANK = 398;
  /** RegularExpression Id. */
  int PERIOD = 399;
  /** RegularExpression Id. */
  int PERMUTE = 400;
  /** RegularExpression Id. */
  int PLACING = 401;
  /** RegularExpression Id. */
  int PLAN = 402;
  /** RegularExpression Id. */
  int PLI = 403;
  /** RegularExpression Id. */
  int PORTION = 404;
  /** RegularExpression Id. */
  int POSITION = 405;
  /** RegularExpression Id. */
  int POSITION_REGEX = 406;
  /** RegularExpression Id. */
  int POWER = 407;
  /** RegularExpression Id. */
  int PRECEDES = 408;
  /** RegularExpression Id. */
  int PRECEDING = 409;
  /** RegularExpression Id. */
  int PRECISION = 410;
  /** RegularExpression Id. */
  int PREPARE = 411;
  /** RegularExpression Id. */
  int PRESERVE = 412;
  /** RegularExpression Id. */
  int PREV = 413;
  /** RegularExpression Id. */
  int PRIMARY = 414;
  /** RegularExpression Id. */
  int PRIOR = 415;
  /** RegularExpression Id. */
  int PRIVILEGES = 416;
  /** RegularExpression Id. */
  int PROCEDURE = 417;
  /** RegularExpression Id. */
  int PUBLIC = 418;
  /** RegularExpression Id. */
  int QUARTER = 419;
  /** RegularExpression Id. */
  int RANGE = 420;
  /** RegularExpression Id. */
  int RANK = 421;
  /** RegularExpression Id. */
  int READ = 422;
  /** RegularExpression Id. */
  int READS = 423;
  /** RegularExpression Id. */
  int REAL = 424;
  /** RegularExpression Id. */
  int RECURSIVE = 425;
  /** RegularExpression Id. */
  int REF = 426;
  /** RegularExpression Id. */
  int REFERENCES = 427;
  /** RegularExpression Id. */
  int REFERENCING = 428;
  /** RegularExpression Id. */
  int REGR_AVGX = 429;
  /** RegularExpression Id. */
  int REGR_AVGY = 430;
  /** RegularExpression Id. */
  int REGR_COUNT = 431;
  /** RegularExpression Id. */
  int REGR_INTERCEPT = 432;
  /** RegularExpression Id. */
  int REGR_R2 = 433;
  /** RegularExpression Id. */
  int REGR_SLOPE = 434;
  /** RegularExpression Id. */
  int REGR_SXX = 435;
  /** RegularExpression Id. */
  int REGR_SXY = 436;
  /** RegularExpression Id. */
  int REGR_SYY = 437;
  /** RegularExpression Id. */
  int RELATIVE = 438;
  /** RegularExpression Id. */
  int RELEASE = 439;
  /** RegularExpression Id. */
  int REPEATABLE = 440;
  /** RegularExpression Id. */
  int REPLACE = 441;
  /** RegularExpression Id. */
  int RESET = 442;
  /** RegularExpression Id. */
  int RESPECT = 443;
  /** RegularExpression Id. */
  int RESTART = 444;
  /** RegularExpression Id. */
  int RESTRICT = 445;
  /** RegularExpression Id. */
  int RESULT = 446;
  /** RegularExpression Id. */
  int RETURN = 447;
  /** RegularExpression Id. */
  int RETURNED_CARDINALITY = 448;
  /** RegularExpression Id. */
  int RETURNED_LENGTH = 449;
  /** RegularExpression Id. */
  int RETURNED_OCTET_LENGTH = 450;
  /** RegularExpression Id. */
  int RETURNED_SQLSTATE = 451;
  /** RegularExpression Id. */
  int RETURNING = 452;
  /** RegularExpression Id. */
  int RETURNS = 453;
  /** RegularExpression Id. */
  int REVOKE = 454;
  /** RegularExpression Id. */
  int RIGHT = 455;
  /** RegularExpression Id. */
  int ROLE = 456;
  /** RegularExpression Id. */
  int ROLLBACK = 457;
  /** RegularExpression Id. */
  int ROLLUP = 458;
  /** RegularExpression Id. */
  int ROUTINE = 459;
  /** RegularExpression Id. */
  int ROUTINE_CATALOG = 460;
  /** RegularExpression Id. */
  int ROUTINE_NAME = 461;
  /** RegularExpression Id. */
  int ROUTINE_SCHEMA = 462;
  /** RegularExpression Id. */
  int ROW = 463;
  /** RegularExpression Id. */
  int ROW_COUNT = 464;
  /** RegularExpression Id. */
  int ROW_NUMBER = 465;
  /** RegularExpression Id. */
  int ROWS = 466;
  /** RegularExpression Id. */
  int RUNNING = 467;
  /** RegularExpression Id. */
  int SAVEPOINT = 468;
  /** RegularExpression Id. */
  int SCALAR = 469;
  /** RegularExpression Id. */
  int SCALE = 470;
  /** RegularExpression Id. */
  int SCHEMA = 471;
  /** RegularExpression Id. */
  int SCHEMA_NAME = 472;
  /** RegularExpression Id. */
  int SCOPE = 473;
  /** RegularExpression Id. */
  int SCOPE_CATALOGS = 474;
  /** RegularExpression Id. */
  int SCOPE_NAME = 475;
  /** RegularExpression Id. */
  int SCOPE_SCHEMA = 476;
  /** RegularExpression Id. */
  int SCROLL = 477;
  /** RegularExpression Id. */
  int SEARCH = 478;
  /** RegularExpression Id. */
  int SECOND = 479;
  /** RegularExpression Id. */
  int SECTION = 480;
  /** RegularExpression Id. */
  int SECURITY = 481;
  /** RegularExpression Id. */
  int SEEK = 482;
  /** RegularExpression Id. */
  int SELECT = 483;
  /** RegularExpression Id. */
  int SELF = 484;
  /** RegularExpression Id. */
  int SENSITIVE = 485;
  /** RegularExpression Id. */
  int SEQUENCE = 486;
  /** RegularExpression Id. */
  int SERIALIZABLE = 487;
  /** RegularExpression Id. */
  int SERVER = 488;
  /** RegularExpression Id. */
  int SERVER_NAME = 489;
  /** RegularExpression Id. */
  int SESSION = 490;
  /** RegularExpression Id. */
  int SESSION_USER = 491;
  /** RegularExpression Id. */
  int SET = 492;
  /** RegularExpression Id. */
  int SETS = 493;
  /** RegularExpression Id. */
  int SET_MINUS = 494;
  /** RegularExpression Id. */
  int SHOW = 495;
  /** RegularExpression Id. */
  int SIMILAR = 496;
  /** RegularExpression Id. */
  int SIMPLE = 497;
  /** RegularExpression Id. */
  int SIZE = 498;
  /** RegularExpression Id. */
  int SKIP_ = 499;
  /** RegularExpression Id. */
  int SMALLINT = 500;
  /** RegularExpression Id. */
  int SOME = 501;
  /** RegularExpression Id. */
  int SOURCE = 502;
  /** RegularExpression Id. */
  int SPACE = 503;
  /** RegularExpression Id. */
  int SPECIFIC = 504;
  /** RegularExpression Id. */
  int SPECIFIC_NAME = 505;
  /** RegularExpression Id. */
  int SPECIFICTYPE = 506;
  /** RegularExpression Id. */
  int SQL = 507;
  /** RegularExpression Id. */
  int SQLEXCEPTION = 508;
  /** RegularExpression Id. */
  int SQLSTATE = 509;
  /** RegularExpression Id. */
  int SQLWARNING = 510;
  /** RegularExpression Id. */
  int SQL_BIGINT = 511;
  /** RegularExpression Id. */
  int SQL_BINARY = 512;
  /** RegularExpression Id. */
  int SQL_BIT = 513;
  /** RegularExpression Id. */
  int SQL_BLOB = 514;
  /** RegularExpression Id. */
  int SQL_BOOLEAN = 515;
  /** RegularExpression Id. */
  int SQL_CHAR = 516;
  /** RegularExpression Id. */
  int SQL_CLOB = 517;
  /** RegularExpression Id. */
  int SQL_DATE = 518;
  /** RegularExpression Id. */
  int SQL_DECIMAL = 519;
  /** RegularExpression Id. */
  int SQL_DOUBLE = 520;
  /** RegularExpression Id. */
  int SQL_FLOAT = 521;
  /** RegularExpression Id. */
  int SQL_INTEGER = 522;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY = 523;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_HOUR = 524;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_MINUTE = 525;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_SECOND = 526;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR = 527;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_MINUTE = 528;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_SECOND = 529;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE = 530;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE_TO_SECOND = 531;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MONTH = 532;
  /** RegularExpression Id. */
  int SQL_INTERVAL_SECOND = 533;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR = 534;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR_TO_MONTH = 535;
  /** RegularExpression Id. */
  int SQL_LONGVARBINARY = 536;
  /** RegularExpression Id. */
  int SQL_LONGVARCHAR = 537;
  /** RegularExpression Id. */
  int SQL_LONGVARNCHAR = 538;
  /** RegularExpression Id. */
  int SQL_NCHAR = 539;
  /** RegularExpression Id. */
  int SQL_NCLOB = 540;
  /** RegularExpression Id. */
  int SQL_NUMERIC = 541;
  /** RegularExpression Id. */
  int SQL_NVARCHAR = 542;
  /** RegularExpression Id. */
  int SQL_REAL = 543;
  /** RegularExpression Id. */
  int SQL_SMALLINT = 544;
  /** RegularExpression Id. */
  int SQL_TIME = 545;
  /** RegularExpression Id. */
  int SQL_TIMESTAMP = 546;
  /** RegularExpression Id. */
  int SQL_TINYINT = 547;
  /** RegularExpression Id. */
  int SQL_TSI_DAY = 548;
  /** RegularExpression Id. */
  int SQL_TSI_FRAC_SECOND = 549;
  /** RegularExpression Id. */
  int SQL_TSI_HOUR = 550;
  /** RegularExpression Id. */
  int SQL_TSI_MICROSECOND = 551;
  /** RegularExpression Id. */
  int SQL_TSI_MINUTE = 552;
  /** RegularExpression Id. */
  int SQL_TSI_MONTH = 553;
  /** RegularExpression Id. */
  int SQL_TSI_QUARTER = 554;
  /** RegularExpression Id. */
  int SQL_TSI_SECOND = 555;
  /** RegularExpression Id. */
  int SQL_TSI_WEEK = 556;
  /** RegularExpression Id. */
  int SQL_TSI_YEAR = 557;
  /** RegularExpression Id. */
  int SQL_VARBINARY = 558;
  /** RegularExpression Id. */
  int SQL_VARCHAR = 559;
  /** RegularExpression Id. */
  int SQRT = 560;
  /** RegularExpression Id. */
  int START = 561;
  /** RegularExpression Id. */
  int STATE = 562;
  /** RegularExpression Id. */
  int STATEMENT = 563;
  /** RegularExpression Id. */
  int STATIC = 564;
  /** RegularExpression Id. */
  int STDDEV_POP = 565;
  /** RegularExpression Id. */
  int STDDEV_SAMP = 566;
  /** RegularExpression Id. */
  int STREAM = 567;
  /** RegularExpression Id. */
  int STRUCTURE = 568;
  /** RegularExpression Id. */
  int STYLE = 569;
  /** RegularExpression Id. */
  int SUBCLASS_ORIGIN = 570;
  /** RegularExpression Id. */
  int SUBMULTISET = 571;
  /** RegularExpression Id. */
  int SUBSET = 572;
  /** RegularExpression Id. */
  int SUBSTITUTE = 573;
  /** RegularExpression Id. */
  int SUBSTRING = 574;
  /** RegularExpression Id. */
  int SUBSTRING_REGEX = 575;
  /** RegularExpression Id. */
  int SUCCEEDS = 576;
  /** RegularExpression Id. */
  int SUM = 577;
  /** RegularExpression Id. */
  int SYMMETRIC = 578;
  /** RegularExpression Id. */
  int SYSTEM = 579;
  /** RegularExpression Id. */
  int SYSTEM_TIME = 580;
  /** RegularExpression Id. */
  int SYSTEM_USER = 581;
  /** RegularExpression Id. */
  int TABLE = 582;
  /** RegularExpression Id. */
  int TABLE_NAME = 583;
  /** RegularExpression Id. */
  int TABLESAMPLE = 584;
  /** RegularExpression Id. */
  int TEMPORARY = 585;
  /** RegularExpression Id. */
  int THEN = 586;
  /** RegularExpression Id. */
  int TIES = 587;
  /** RegularExpression Id. */
  int TIME = 588;
  /** RegularExpression Id. */
  int TIMESTAMP = 589;
  /** RegularExpression Id. */
  int TIMESTAMPADD = 590;
  /** RegularExpression Id. */
  int TIMESTAMPDIFF = 591;
  /** RegularExpression Id. */
  int TIMEZONE_HOUR = 592;
  /** RegularExpression Id. */
  int TIMEZONE_MINUTE = 593;
  /** RegularExpression Id. */
  int TINYINT = 594;
  /** RegularExpression Id. */
  int TO = 595;
  /** RegularExpression Id. */
  int TOP_LEVEL_COUNT = 596;
  /** RegularExpression Id. */
  int TRAILING = 597;
  /** RegularExpression Id. */
  int TRANSACTION = 598;
  /** RegularExpression Id. */
  int TRANSACTIONS_ACTIVE = 599;
  /** RegularExpression Id. */
  int TRANSACTIONS_COMMITTED = 600;
  /** RegularExpression Id. */
  int TRANSACTIONS_ROLLED_BACK = 601;
  /** RegularExpression Id. */
  int TRANSFORM = 602;
  /** RegularExpression Id. */
  int TRANSFORMS = 603;
  /** RegularExpression Id. */
  int TRANSLATE = 604;
  /** RegularExpression Id. */
  int TRANSLATE_REGEX = 605;
  /** RegularExpression Id. */
  int TRANSLATION = 606;
  /** RegularExpression Id. */
  int TREAT = 607;
  /** RegularExpression Id. */
  int TRIGGER = 608;
  /** RegularExpression Id. */
  int TRIGGER_CATALOG = 609;
  /** RegularExpression Id. */
  int TRIGGER_NAME = 610;
  /** RegularExpression Id. */
  int TRIGGER_SCHEMA = 611;
  /** RegularExpression Id. */
  int TRIM = 612;
  /** RegularExpression Id. */
  int TRIM_ARRAY = 613;
  /** RegularExpression Id. */
  int TRUE = 614;
  /** RegularExpression Id. */
  int TRUNCATE = 615;
  /** RegularExpression Id. */
  int TYPE = 616;
  /** RegularExpression Id. */
  int UESCAPE = 617;
  /** RegularExpression Id. */
  int UNBOUNDED = 618;
  /** RegularExpression Id. */
  int UNCOMMITTED = 619;
  /** RegularExpression Id. */
  int UNCONDITIONAL = 620;
  /** RegularExpression Id. */
  int UNDER = 621;
  /** RegularExpression Id. */
  int UNION = 622;
  /** RegularExpression Id. */
  int UNIQUE = 623;
  /** RegularExpression Id. */
  int UNKNOWN = 624;
  /** RegularExpression Id. */
  int UNNAMED = 625;
  /** RegularExpression Id. */
  int UNNEST = 626;
  /** RegularExpression Id. */
  int UPDATE = 627;
  /** RegularExpression Id. */
  int UPPER = 628;
  /** RegularExpression Id. */
  int UPSERT = 629;
  /** RegularExpression Id. */
  int USAGE = 630;
  /** RegularExpression Id. */
  int USER = 631;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CATALOG = 632;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CODE = 633;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_NAME = 634;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_SCHEMA = 635;
  /** RegularExpression Id. */
  int USING = 636;
  /** RegularExpression Id. */
  int UTF8 = 637;
  /** RegularExpression Id. */
  int UTF16 = 638;
  /** RegularExpression Id. */
  int UTF32 = 639;
  /** RegularExpression Id. */
  int VALUE = 640;
  /** RegularExpression Id. */
  int VALUES = 641;
  /** RegularExpression Id. */
  int VALUE_OF = 642;
  /** RegularExpression Id. */
  int VAR_POP = 643;
  /** RegularExpression Id. */
  int VAR_SAMP = 644;
  /** RegularExpression Id. */
  int VARBINARY = 645;
  /** RegularExpression Id. */
  int VARCHAR = 646;
  /** RegularExpression Id. */
  int VARYING = 647;
  /** RegularExpression Id. */
  int VERSION = 648;
  /** RegularExpression Id. */
  int VERSIONING = 649;
  /** RegularExpression Id. */
  int VIEW = 650;
  /** RegularExpression Id. */
  int WEEK = 651;
  /** RegularExpression Id. */
  int WHEN = 652;
  /** RegularExpression Id. */
  int WHENEVER = 653;
  /** RegularExpression Id. */
  int WHERE = 654;
  /** RegularExpression Id. */
  int WIDTH_BUCKET = 655;
  /** RegularExpression Id. */
  int WINDOW = 656;
  /** RegularExpression Id. */
  int WITH = 657;
  /** RegularExpression Id. */
  int WITHIN = 658;
  /** RegularExpression Id. */
  int WITHOUT = 659;
  /** RegularExpression Id. */
  int WORK = 660;
  /** RegularExpression Id. */
  int WRAPPER = 661;
  /** RegularExpression Id. */
  int WRITE = 662;
  /** RegularExpression Id. */
  int XML = 663;
  /** RegularExpression Id. */
  int YEAR = 664;
  /** RegularExpression Id. */
  int ZONE = 665;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER_LITERAL = 666;
  /** RegularExpression Id. */
  int APPROX_NUMERIC_LITERAL = 667;
  /** RegularExpression Id. */
  int DECIMAL_NUMERIC_LITERAL = 668;
  /** RegularExpression Id. */
  int EXPONENT = 669;
  /** RegularExpression Id. */
  int HEXDIGIT = 670;
  /** RegularExpression Id. */
  int WHITESPACE = 671;
  /** RegularExpression Id. */
  int BINARY_STRING_LITERAL = 672;
  /** RegularExpression Id. */
  int QUOTED_STRING = 673;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING = 674;
  /** RegularExpression Id. */
  int PREFIXED_STRING_LITERAL = 675;
  /** RegularExpression Id. */
  int UNICODE_STRING_LITERAL = 676;
  /** RegularExpression Id. */
  int CHARSETNAME = 677;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_ESCAPE_CHAR = 678;
  /** RegularExpression Id. */
  int LPAREN = 679;
  /** RegularExpression Id. */
  int RPAREN = 680;
  /** RegularExpression Id. */
  int LBRACE_D = 681;
  /** RegularExpression Id. */
  int LBRACE_T = 682;
  /** RegularExpression Id. */
  int LBRACE_TS = 683;
  /** RegularExpression Id. */
  int LBRACE_FN = 684;
  /** RegularExpression Id. */
  int LBRACE = 685;
  /** RegularExpression Id. */
  int RBRACE = 686;
  /** RegularExpression Id. */
  int LBRACKET = 687;
  /** RegularExpression Id. */
  int RBRACKET = 688;
  /** RegularExpression Id. */
  int SEMICOLON = 689;
  /** RegularExpression Id. */
  int DOT = 690;
  /** RegularExpression Id. */
  int COMMA = 691;
  /** RegularExpression Id. */
  int EQ = 692;
  /** RegularExpression Id. */
  int GT = 693;
  /** RegularExpression Id. */
  int LT = 694;
  /** RegularExpression Id. */
  int HOOK = 695;
  /** RegularExpression Id. */
  int COLON = 696;
  /** RegularExpression Id. */
  int LE = 697;
  /** RegularExpression Id. */
  int GE = 698;
  /** RegularExpression Id. */
  int NE = 699;
  /** RegularExpression Id. */
  int NE2 = 700;
  /** RegularExpression Id. */
  int PLUS = 701;
  /** RegularExpression Id. */
  int MINUS = 702;
  /** RegularExpression Id. */
  int STAR = 703;
  /** RegularExpression Id. */
  int SLASH = 704;
  /** RegularExpression Id. */
  int PERCENT_REMAINDER = 705;
  /** RegularExpression Id. */
  int CONCAT = 706;
  /** RegularExpression Id. */
  int NAMED_ARGUMENT_ASSIGNMENT = 707;
  /** RegularExpression Id. */
  int DOUBLE_PERIOD = 708;
  /** RegularExpression Id. */
  int QUOTE = 709;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 710;
  /** RegularExpression Id. */
  int VERTICAL_BAR = 711;
  /** RegularExpression Id. */
  int CARET = 712;
  /** RegularExpression Id. */
  int DOLLAR = 713;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 721;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 722;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 723;
  /** RegularExpression Id. */
  int BRACKET_QUOTED_IDENTIFIER = 725;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 726;
  /** RegularExpression Id. */
  int BACK_QUOTED_IDENTIFIER = 727;
  /** RegularExpression Id. */
  int COLLATION_ID = 728;
  /** RegularExpression Id. */
  int IDENTIFIER = 729;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_IDENTIFIER = 730;
  /** RegularExpression Id. */
  int LETTER = 731;
  /** RegularExpression Id. */
  int DIGIT = 732;
  /** RegularExpression Id. */
  int BEL = 733;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DQID = 1;
  /** Lexical state. */
  int BTID = 2;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOUR\"",
    "\"IDENTITY\"",
    "\"IGNORE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"JSON_VALUE\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESPECT\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"ZONE\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<DOUBLE_QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 719>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 724>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<COLLATION_ID>",
    "<IDENTIFIER>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
